export const HIPPOMEMO_CSS = [
  '.hippomemo-section[data-plugin="dsh-hippomemo"] { display: flex; flex-direction: column; gap: 16px; padding: 4px 2px 24px; color: var(--dsw-alias-label-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-title { margin: 0; color: var(--dsw-alias-label-primary); font-size: 18px; line-height: 26px; font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-intro { margin: 0; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-toolbar { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-toolbar input, [data-plugin="dsh-hippomemo"] .hippomemo-toolbar select { padding: 6px 8px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); font: inherit; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-search-wrap { position: relative; display: inline-flex; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-search { min-width: 240px; padding-left: 30px !important; padding-right: 30px !important; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-search-icon { position: absolute; left: 9px; display: inline-flex; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.6; pointer-events: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-search-clear { position: absolute; right: 6px; display: inline-flex; align-items: center; justify-content: center; border: none; background: none; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.6; padding: 2px; cursor: pointer; border-radius: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-search-clear:hover { opacity: 1; background: var(--dsw-alias-interactive-bg-hover); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-order { display: inline-flex; align-items: center; justify-content: center; width: 34px; height: 34px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-order:hover { background: var(--dsw-alias-interactive-bg-hover); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-button-danger { color: var(--dsw-alias-state-error-primary, var(--dsw-static-red-500)) !important; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select { display: inline-flex; align-items: center; justify-content: space-between; gap: 8px; min-width: 132px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); font: inherit; font-size: 13px; line-height: 20px; padding: 6px 8px; cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select:hover { background: var(--dsw-alias-interactive-bg-hover); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select-label { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select-chevron { display: inline-flex; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; transition: transform 120ms ease; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select-open .hippomemo-select-chevron { transform: rotate(180deg); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-list { display: flex; flex-direction: column; gap: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card { border: 1px solid var(--dsw-alias-border-l1); border-radius: 12px; background: var(--dsw-alias-bg-layer-2); padding: 4px; transition: border-color 120ms ease; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card:hover { border-color: var(--dsw-alias-interactive-bg-hover-accent, var(--dsw-alias-border-l1)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-main { display: block; width: 100%; margin: 0; padding: 12px 14px; border: none; background: none; color: inherit; font: inherit; text-align: left; cursor: pointer; border-radius: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-main:hover { background: var(--dsw-alias-interactive-bg-hover); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-head { display: flex; justify-content: space-between; gap: 8px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-title { min-width: 0; color: var(--dsw-alias-label-primary); font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-actions { display: flex; flex-wrap: wrap; gap: 4px; padding: 0 8px 8px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-meta { display: flex; flex-wrap: wrap; gap: 8px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-usage { display: flex; flex-wrap: wrap; gap: 8px 14px; align-items: center; border: 1px solid var(--dsw-alias-border-l1); border-radius: 12px; background: var(--dsw-alias-bg-layer-2); padding: 8px 12px; color: var(--dsw-alias-label-primary); font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-usage-label { font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-usage-hint { color: var(--dsw-alias-state-warn-primary, var(--dsw-alias-label-primary)); opacity: 0.9; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-content { white-space: pre-wrap; margin: 8px 0 0; color: var(--dsw-alias-label-primary); font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-clamp { display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; white-space: normal; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-form { display: flex; flex-direction: column; gap: 8px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 12px; background: var(--dsw-alias-bg-layer-2); padding: 12px 14px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-form label { display: flex; flex-direction: column; gap: 4px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-form input, [data-plugin="dsh-hippomemo"] .hippomemo-form textarea, [data-plugin="dsh-hippomemo"] .hippomemo-form select { border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); padding: 6px 8px; font: inherit; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-form textarea { min-height: 96px; resize: vertical; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-error { color: var(--dsw-alias-state-error-primary, var(--dsw-static-red-500)); font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-status, [data-plugin="dsh-hippomemo"] .hippomemo-empty { color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-retry { margin-left: 8px; border: none; border-radius: 8px; background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); font: inherit; font-size: 12px; line-height: 20px; padding: 2px 8px; cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager { display: flex; flex-wrap: wrap; gap: 12px; align-items: center; justify-content: space-between; border-top: 1px solid var(--dsw-alias-border-l1); padding-top: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-meta { color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-controls { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-btn { display: inline-flex; align-items: center; gap: 4px; min-width: 30px; justify-content: center; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); font: inherit; font-size: 12px; line-height: 20px; padding: 4px 8px; cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-btn:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-btn:disabled { opacity: 0.4; cursor: default; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-active { border-color: var(--dsw-alias-interactive-bg-hover-accent, var(--dsw-alias-border-l1)); background: var(--dsw-alias-interactive-bg-hover); font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-gap { color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.6; padding: 0 2px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-kind-pill { text-transform: capitalize; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-kind-insight, [data-plugin="dsh-hippomemo"] .hippomemo-kind-fact { color: var(--dsw-alias-brand-primary, var(--dsw-alias-label-primary)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-kind-decision { color: var(--dsw-static-deepseek-450, var(--dsw-alias-label-primary)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-kind-preference { color: var(--dsw-alias-state-warn-primary, var(--dsw-alias-label-primary)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-kind-constraint { color: var(--dsw-alias-state-error-primary, var(--dsw-static-red-500)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-status-archived, [data-plugin="dsh-hippomemo"] .hippomemo-status-superseded { opacity: 0.6; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail { display: flex; flex-direction: column; gap: 14px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-nav { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; justify-content: space-between; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-actions { display: flex; flex-wrap: wrap; gap: 4px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-head { display: flex; flex-direction: column; gap: 8px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-title { margin: 0; color: var(--dsw-alias-label-primary); font-size: 17px; line-height: 26px; font-weight: 600; overflow-wrap: anywhere; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-pills { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-content { margin: 0; padding: 12px 14px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 12px; background: var(--dsw-alias-bg-layer-2); max-height: 420px; overflow-y: auto; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-tag-list { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-tag-label, [data-plugin="dsh-hippomemo"] .hippomemo-related-label { color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-tag-pill { color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-facts { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 8px 16px; margin: 0; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-fact { display: flex; flex-direction: column; gap: 2px; min-width: 0; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-fact dt { color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-fact dd { margin: 0; color: var(--dsw-alias-label-primary); font-size: 13px; line-height: 20px; overflow-wrap: anywhere; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related { display: flex; flex-direction: column; gap: 8px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-list { display: flex; flex-direction: column; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-item { display: flex; flex-direction: column; gap: 2px; padding: 8px 10px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: inherit; font: inherit; text-align: left; cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-item:hover { background: var(--dsw-alias-interactive-bg-hover); border-color: var(--dsw-alias-interactive-bg-hover-accent, var(--dsw-alias-border-l1)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-title { color: var(--dsw-alias-label-primary); font-weight: 600; font-size: 13px; line-height: 20px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-meta { color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 12px; line-height: 18px; }',
].join('\n')
