/**
 * hippomemo client styles — v3 architecture (4-quadrant + brain strip).
 * Principles:
 *  1. Host-only --dsw-* tokens; no plugin-owned hex palette (auto light/dark).
 *  2. Single brand accent: preference is the only kind tinted blue; rest grayscale.
 *  3. Visual weight: brain strip > quadrants > list rows > meta grey.
 *  4. Every rule scoped under [data-plugin="dsh-hippomemo"] to avoid leakage.
 *  5. CSS-only content-visibility for long lists; reduced-motion animation toggle.
 */
export const HIPPOMEMO_CSS = [
  '[data-plugin="dsh-hippomemo"] .hippomemo-section { display: flex; flex-direction: column; gap: 14px; padding: 4px 2px 24px; color: var(--dsw-alias-label-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-tab { display: flex; flex-direction: column; gap: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-title { margin: 0; font-size: 16px; line-height: 24px; font-weight: 600; letter-spacing: -0.01em; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-intro { margin: 0; font-size: 12px; line-height: 18px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-tabs { align-self: flex-start; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-toolbar { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-panel-head { display: flex; align-items: center; gap: 8px; padding-bottom: 4px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-panel-title { margin: 0; font-size: 13px; line-height: 20px; font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-panel-count { margin-left: auto; font-size: 11px; line-height: 16px; color: var(--dsw-alias-label-tertiary, var(--dsw-alias-label-secondary)); font-variant-numeric: tabular-nums; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-panel { display: flex; flex-direction: column; gap: 6px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; background: var(--dsw-alias-bg-layer-2); padding: 10px 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-strip { display: flex; flex-direction: column; gap: 8px; padding-top: 6px; border-top: 1px dashed var(--dsw-alias-border-l1); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-row { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-region { display: inline-flex; align-items: center; gap: 6px; padding: 4px 10px; border-radius: 999px; border: 1px solid transparent; background: transparent; color: inherit; font: inherit; font-size: 12px; line-height: 18px; cursor: pointer; transition: background 160ms, border-color 160ms; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-region:hover { background: var(--dsw-alias-interactive-bg-hover); border-color: var(--dsw-alias-label-dimmed, var(--dsw-alias-border-l1)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-dot { width: 10px; height: 10px; border-radius: 50%; flex: none; position: relative; display: inline-block; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-name { font-weight: 500; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-val { font-size: 11px; color: var(--dsw-alias-label-tertiary, var(--dsw-alias-label-secondary)); font-variant-numeric: tabular-nums; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-spacer { flex: 1; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-chev { transition: transform 160ms; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-chev-up { transform: rotate(180deg); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-narration { display: flex; align-items: center; gap: 8px; font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-narration-lbl { color: var(--dsw-alias-label-tertiary); font-size: 11px; flex: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-narration-txt { color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-expand { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 10px; padding-top: 8px; border-top: 1px solid var(--dsw-alias-border-l1); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-card { border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; padding: 10px 12px; background: var(--dsw-alias-bg-layer-2, transparent); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-card-title { font-size: 12px; font-weight: 600; margin: 0 0 4px; display: flex; align-items: center; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-card-desc { font-size: 11px; line-height: 16px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); margin: 0 0 4px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-card-role { font-size: 10px; color: var(--dsw-alias-label-tertiary); }',
  '@keyframes hippomemo-pulse-pfc { 0% { box-shadow: 0 0 0 0 rgba(37,99,235,.55); } 100% { box-shadow: 0 0 0 14px rgba(37,99,235,0); } }',
  '@keyframes hippomemo-pulse-amy { 0% { box-shadow: 0 0 0 0 rgba(220,38,38,.55); } 100% { box-shadow: 0 0 0 16px rgba(220,38,38,0); } }',
  '@keyframes hippomemo-pulse-hippo { 0% { box-shadow: 0 0 0 0 rgba(124,58,237,.55); } 100% { box-shadow: 0 0 0 14px rgba(124,58,237,0); } }',
  '@keyframes hippomemo-pulse-cortex { 0% { box-shadow: 0 0 0 0 rgba(71,85,105,.45); } 100% { box-shadow: 0 0 0 12px rgba(71,85,105,0); } }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-region-anim-pfc .hippomemo-brain-dot { animation: hippomemo-pulse-pfc 0.9s ease-out; border-radius: 50%; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-region-anim-amy .hippomemo-brain-dot { animation: hippomemo-pulse-amy 0.9s ease-out; border-radius: 50%; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-region-anim-hippo .hippomemo-brain-dot { animation: hippomemo-pulse-hippo 0.9s ease-out; border-radius: 50%; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-brain-region-anim-cortex .hippomemo-brain-dot { animation: hippomemo-pulse-cortex 0.9s ease-out; border-radius: 50%; }',
  '@media (prefers-reduced-motion: reduce) {\n    [data-plugin="dsh-hippomemo"] .hippomemo-brain-region-anim-pfc .hippomemo-brain-dot,\n    [data-plugin="dsh-hippomemo"] .hippomemo-brain-region-anim-amy .hippomemo-brain-dot,\n    [data-plugin="dsh-hippomemo"] .hippomemo-brain-region-anim-hippo .hippomemo-brain-dot,\n    [data-plugin="dsh-hippomemo"] .hippomemo-brain-region-anim-cortex .hippomemo-brain-dot { animation: none; }\n  }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-quadrant-empty { display: flex; align-items: center; gap: 6px; color: var(--dsw-alias-label-tertiary); font-size: 12px; line-height: 18px; margin: 0; padding: 6px 0; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-list { display: flex; flex-direction: column; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-item { display: flex; align-items: center; gap: 10px; padding: 9px 12px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2, transparent); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-icon { width: 22px; height: 22px; border-radius: 6px; display: inline-flex; align-items: center; justify-content: center; flex: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-icon-warn { background: var(--dsw-alias-state-warn-tint, rgba(217,119,6,.12)); color: var(--dsw-alias-state-warn-primary, #D97706); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-icon-info { background: var(--dsw-alias-state-info-tint, rgba(37,99,235,.12)); color: var(--dsw-alias-brand-primary, #2563EB); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-icon-danger { background: var(--dsw-alias-state-error-tint, rgba(220,38,38,.12)); color: var(--dsw-alias-state-error-primary, #DC2626); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-body { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 2px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-title { font-size: 13px; line-height: 18px; font-weight: 500; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-desc { display: flex; flex-wrap: wrap; gap: 6px 10px; align-items: center; font-size: 11px; line-height: 16px; color: var(--dsw-alias-label-tertiary, var(--dsw-alias-label-secondary)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-reason { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 360px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-meta { color: var(--dsw-alias-label-tertiary); font-variant-numeric: tabular-nums; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-act { flex: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-todo-kind { font-size: 10px; padding: 1px 6px; text-transform: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-recall-list { list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 4px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-recall-item { display: flex; flex-direction: column; gap: 2px; padding: 6px 8px; border-radius: 6px; border-left: 3px solid var(--dsw-alias-border-l2, transparent); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-recall-item-injected { border-left-color: var(--dsw-alias-brand-primary, #2563EB); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-recall-item-suppressed { border-left-color: var(--dsw-alias-state-warn-primary, #D97706); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-recall-item-cited { border-left-color: var(--dsw-alias-state-success-primary, #16A34A); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-recall-when { font-size: 11px; color: var(--dsw-alias-label-tertiary); font-variant-numeric: tabular-nums; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-recall-what { font-size: 13px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-recall-m { font-weight: 500; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-recall-sub { color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); font-size: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-zone { display: flex; flex-direction: column; gap: 8px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-strip { border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; overflow: hidden; background: var(--dsw-alias-bg-layer-2); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-head { display: flex; align-items: center; gap: 8px; padding: 8px 12px; background: var(--dsw-alias-bg-layer-1, var(--dsw-alias-bg-layer-2)); border-bottom: 1px solid var(--dsw-alias-border-l1); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-head-title { font-size: 12px; font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-head-meta { margin-left: auto; font-size: 11px; color: var(--dsw-alias-label-tertiary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-list { list-style: none; padding: 0; margin: 0; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-row { display: flex; align-items: center; gap: 10px; padding: 10px 12px; border-bottom: 1px solid var(--dsw-alias-border-l1); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-row:last-child { border-bottom: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-row-confirmed { background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #16A34A) 4%, transparent); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-source { font-size: 10px; padding: 1px 8px; flex: none; font-weight: 500; text-transform: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-source-auto { background: var(--dsw-alias-state-error-tint, rgba(220,38,38,.10)); color: var(--dsw-alias-state-error-primary, #DC2626); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-source-manual { background: var(--dsw-alias-state-info-tint, rgba(37,99,235,.10)); color: var(--dsw-alias-brand-primary, #2563EB); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-body { flex: 1; min-width: 0; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-text { font-size: 13px; line-height: 20px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-stats { display: flex; flex-wrap: wrap; gap: 0 6px; align-items: center; font-size: 11px; line-height: 16px; color: var(--dsw-alias-label-tertiary); margin-top: 2px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-hit { color: var(--dsw-alias-state-success-primary, #16A34A); font-weight: 500; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-decay { color: var(--dsw-alias-state-warn-primary, #D97706); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-ops { display: flex; gap: 4px; flex: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-op { appearance: none; cursor: pointer; color: var(--dsw-alias-label-secondary); background: none; border: 0; padding: 4px 8px; font: inherit; font-size: 11px; line-height: 16px; border-radius: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-op:hover { background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-op-confirm:hover { background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #16A34A) 12%, transparent); color: var(--dsw-alias-state-success-primary, #16A34A); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pref-op-forget:hover { background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #DC2626) 12%, transparent); color: var(--dsw-alias-state-error-primary, #DC2626); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-memory-panel { display: flex; flex-direction: column; gap: 8px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-search { flex: 1; min-width: 160px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select { display: inline-flex; align-items: center; justify-content: space-between; gap: 6px; min-width: 112px; height: 32px; padding: 0 8px 0 10px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-secondary); font: inherit; font-size: 12px; line-height: 20px; cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select:hover { background: var(--dsw-alias-interactive-bg-hover); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select-label { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select-chevron { display: inline-flex; color: var(--dsw-alias-label-tertiary); transition: transform 120ms ease; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-select-open .hippomemo-select-chevron { transform: rotate(180deg); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-list { display: flex; flex-direction: column; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row { content-visibility: auto; contain-intrinsic-size: auto 56px; display: grid; grid-template-columns: 1fr auto; gap: 12px; align-items: center; padding: 10px 12px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; background: var(--dsw-alias-bg-layer-2); margin-top: 6px; transition: border-color 120ms ease; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row:hover { border-color: var(--dsw-alias-interactive-bg-hover-accent, var(--dsw-alias-border-l1)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row-archived { opacity: 0.6; background: var(--dsw-alias-bg-layer-1, var(--dsw-alias-bg-layer-2)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row-main { display: flex; align-items: center; gap: 8px; min-width: 0; margin: 0; padding: 0; border: none; background: none; color: inherit; font: inherit; text-align: left; cursor: pointer; overflow: hidden; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row-title-wrap { display: flex; flex-direction: column; gap: 2px; min-width: 0; flex: 1; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row-title { min-width: 0; flex: 1; font-size: 13px; line-height: 20px; font-weight: 500; color: var(--dsw-alias-label-primary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row-meta { display: flex; flex-wrap: wrap; gap: 4px 8px; margin-top: 2px; font-size: 11px; line-height: 16px; color: var(--dsw-alias-label-tertiary, var(--dsw-alias-label-secondary)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row-meta-sep { color: var(--dsw-alias-border-l2, var(--dsw-alias-label-tertiary)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row-actions { display: flex; align-items: center; gap: 2px; flex: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-icon-btn { display: inline-flex; align-items: center; justify-content: center; width: 28px; height: 28px; border: 1px solid transparent; border-radius: 6px; background: transparent; color: var(--dsw-alias-label-tertiary); cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-icon-btn:hover { background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-icon-btn-danger:hover { background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #DC2626) 14%, transparent); color: var(--dsw-alias-state-error-primary, #DC2626); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pill { font-size: 10px; padding: 1px 8px; flex: none; font-weight: 500; text-transform: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pill-preference { background: color-mix(in srgb, var(--dsw-alias-brand-primary, #2563EB) 10%, transparent); color: var(--dsw-alias-brand-primary, #2563EB); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pill .hippomemo-pill-icon { display: inline-flex; color: inherit; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-kind-pill { text-transform: none; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-kind-preference { background: color-mix(in srgb, var(--dsw-alias-brand-primary, #2563EB) 10%, transparent); color: var(--dsw-alias-brand-primary, #2563EB); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-kind-insight, [data-plugin="dsh-hippomemo"] .hippomemo-kind-fact, [data-plugin="dsh-hippomemo"] .hippomemo-kind-decision, [data-plugin="dsh-hippomemo"] .hippomemo-kind-constraint { color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-status-archived, [data-plugin="dsh-hippomemo"] .hippomemo-status-superseded { color: var(--dsw-alias-label-tertiary); text-decoration: line-through; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-status-candidate { color: var(--dsw-alias-state-warn-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-proven-yes { color: var(--dsw-alias-state-success-primary); font-weight: 500; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-proven-no { color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-scope-pill, [data-plugin="dsh-hippomemo"] .hippomemo-status-pill, [data-plugin="dsh-hippomemo"] .hippomemo-proven-pill { background: var(--dsw-alias-bg-layer-3, var(--dsw-alias-bg-layer-2)); color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-status, [data-plugin="dsh-hippomemo"] .hippomemo-empty { color: var(--dsw-alias-label-secondary); font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-error { color: var(--dsw-alias-state-error-primary); font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; justify-content: space-between; border-top: 1px solid var(--dsw-alias-border-l1); padding-top: 12px; margin-top: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-meta { font-size: 12px; color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-controls { display: flex; flex-wrap: wrap; gap: 4px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-pager-gap { color: var(--dsw-alias-label-tertiary); padding: 0 2px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-modal-body { display: flex; flex-direction: column; gap: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-modal-footer { display: flex; justify-content: flex-end; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-pills { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-detail-content { margin: 0; padding: 12px 14px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; background: var(--dsw-alias-bg-layer-2); max-height: 360px; overflow-y: auto; white-space: pre-wrap; font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-tag-list { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-tag-label { font-size: 12px; color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-tag-pill { color: var(--dsw-alias-label-secondary); font-size: 11px; padding: 1px 8px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-facts { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 8px 16px; margin: 0; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-fact { display: flex; flex-direction: column; gap: 2px; min-width: 0; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-fact dt { font-size: 12px; color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-fact dd { margin: 0; font-size: 13px; line-height: 20px; overflow-wrap: anywhere; font-variant-numeric: tabular-nums; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-fact-spark { color: var(--dsw-alias-brand-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-source-spark-pill { display: inline-flex; align-items: center; gap: 4px; color: var(--dsw-alias-brand-primary); font-size: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-source-spark-id { font-family: var(--ds-font-family-code, ui-monospace, monospace); font-size: 11px; opacity: 0.8; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-row-spark { display: inline-flex; color: var(--dsw-alias-brand-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-lineage { margin-top: 8px; border-top: 1px solid var(--dsw-alias-border-l1); padding-top: 10px; display: flex; flex-direction: column; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-lineage-title { font-size: 12px; font-weight: 600; margin: 0; display: flex; align-items: center; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-lineage-row { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; font-size: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-lineage-node { padding: 3px 10px; border-radius: 8px; border: 1px solid var(--dsw-alias-border-l1); font-size: 11px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-lineage-spark { color: var(--dsw-static-violet-500, #7C3AED); border-color: var(--dsw-static-violet-500, #7C3AED); background: color-mix(in srgb, var(--dsw-static-violet-500, #7C3AED) 10%, transparent); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-lineage-crystal { color: var(--dsw-alias-label-secondary); background: var(--dsw-alias-bg-layer-2); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-lineage-hippo { color: var(--dsw-alias-label-primary); border-color: var(--dsw-alias-border-l2, var(--dsw-alias-border-l1)); background: var(--dsw-alias-bg-layer-1, var(--dsw-alias-bg-layer-2)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-lineage-arrow { color: var(--dsw-alias-label-tertiary); font-size: 11px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-lineage-note { font-size: 11px; color: var(--dsw-alias-label-tertiary); margin: 0; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related { display: flex; flex-direction: column; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-label { font-size: 12px; color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-list { display: flex; flex-direction: column; gap: 4px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-item { display: flex; flex-direction: column; gap: 2px; padding: 8px 10px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: inherit; font: inherit; text-align: left; cursor: pointer; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-item:hover { background: var(--dsw-alias-interactive-bg-hover); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-title { font-weight: 600; font-size: 13px; line-height: 20px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-related-meta { font-size: 12px; color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-edit-modal-body { display: flex; flex-direction: column; gap: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-edit-modal-footer { display: flex; justify-content: flex-end; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-form-label { display: flex; flex-direction: column; gap: 4px; font-size: 12px; line-height: 18px; color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-button-danger { color: var(--dsw-alias-state-error-primary) !important; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-panel { display: flex; flex-direction: column; gap: 14px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-meta { display: flex; flex-wrap: wrap; gap: 8px 14px; font-size: 12px; line-height: 18px; color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-usage { display: flex; flex-wrap: wrap; gap: 8px 14px; align-items: center; border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; background: var(--dsw-alias-bg-layer-2); padding: 8px 12px; font-size: 12px; color: var(--dsw-alias-label-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-usage-label { font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-usage-hint { color: var(--dsw-alias-state-warn-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-chart-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-chart-card { display: flex; flex-direction: column; gap: 10px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; background: var(--dsw-alias-bg-layer-2); padding: 12px 14px; min-width: 0; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-chart-card-wide { grid-column: 1 / -1; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-chart-title { font-size: 13px; line-height: 20px; font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-evolve-report { display: flex; flex-direction: column; gap: 12px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; background: var(--dsw-alias-bg-layer-2); padding: 12px 14px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-evolve-block-title { font-size: 12px; line-height: 18px; color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-evolve-review, [data-plugin="dsh-hippomemo"] .hippomemo-evolve-actions { display: flex; flex-direction: column; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-evolve-verdict, [data-plugin="dsh-hippomemo"] .hippomemo-evolve-action { display: flex; align-items: center; gap: 8px; min-width: 0; font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-evolve-verdict-id, [data-plugin="dsh-hippomemo"] .hippomemo-evolve-action-id { flex: none; font-family: var(--ds-font-family-code, ui-monospace, monospace); font-size: 12px; color: var(--dsw-alias-label-secondary); opacity: 0.7; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-evolve-verdict-reason, [data-plugin="dsh-hippomemo"] .hippomemo-evolve-action-reason { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-evolve-kind { flex: none; text-transform: none; font-size: 11px; padding: 1px 8px; opacity: 0.85; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-verdict-keep { color: var(--dsw-alias-state-success-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-verdict-noise { color: var(--dsw-alias-state-warn-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card { list-style: none; border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; background: var(--dsw-alias-bg-layer-2); transition: border-color 160ms, background 160ms; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card:hover { border-color: var(--dsw-alias-label-dimmed, var(--dsw-alias-border-l1)); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-open { background: var(--dsw-alias-bg-layer-2); border-color: var(--dsw-alias-label-dimmed); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-header { appearance: none; width: 100%; font: inherit; color: inherit; text-align: left; cursor: pointer; background: none; border: 0; border-radius: 10px; align-items: center; gap: 10px; padding: 12px 14px; display: flex; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-header:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: -2px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-head-text { flex-direction: column; flex: 1; gap: 2px; min-width: 0; display: flex; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-name { color: var(--dsw-alias-label-primary); font-size: 14px; font-weight: 600; line-height: 20px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-description { color: var(--dsw-alias-label-tertiary); font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-pending { white-space: nowrap; background: var(--dsw-alias-bg-module-platform, var(--dsw-alias-bg-layer-3)); color: var(--dsw-alias-label-secondary); border-radius: 999px; flex: none; padding: 1px 8px; font-size: 11px; font-weight: 500; line-height: 17px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-chevron { color: var(--dsw-alias-label-tertiary); flex: none; width: 8px; height: 8px; border-right: 1.6px solid currentColor; border-bottom: 1.6px solid currentColor; transform: rotate(45deg); transition: transform 160ms; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-chevron-open { transform: rotate(225deg); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-body { border-top: 1px solid var(--dsw-alias-border-l1); margin: 0 14px; padding: 4px 0 12px; display: flex; flex-direction: column; gap: 12px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-readonly { color: var(--dsw-alias-label-tertiary); margin: 10px 0 0; font-size: 12px; line-height: 18px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-field { flex-direction: column; gap: 5px; display: flex; margin-top: 10px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-field-head { align-items: center; gap: 8px; display: flex; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-field-label { color: var(--dsw-alias-label-secondary); flex: 1; font-size: 12px; line-height: 18px; font-weight: 500; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-field-badges { align-items: center; gap: 6px; display: flex; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-field-input { width: 100%; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-field-foot { align-items: center; gap: 10px; display: flex; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-hint { color: var(--dsw-alias-label-tertiary); flex: 1; margin: 0; font-size: 11px; line-height: 16px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-reset { appearance: none; font: inherit; cursor: pointer; color: var(--dsw-alias-label-secondary); background: none; border: 0; padding: 0; font-size: 11px; line-height: 16px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-reset:hover:not(:disabled) { color: var(--dsw-alias-brand-primary); text-decoration: underline; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-choice-row { align-items: center; gap: 6px; flex-wrap: wrap; display: flex; margin-top: 4px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-choice { appearance: none; cursor: pointer; font: inherit; font-size: 12px; line-height: 18px; padding: 3px 10px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 999px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-secondary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-choice:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-choice-active { background: var(--dsw-alias-brand-primary); color: var(--dsw-alias-bg-layer-2); border-color: var(--dsw-alias-brand-primary); font-weight: 600; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-advanced { border-top: 1px dashed var(--dsw-alias-border-l1); margin-top: 4px; padding-top: 8px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-advanced-summary { appearance: none; font: inherit; cursor: pointer; color: var(--dsw-alias-label-secondary); background: none; border: 0; padding: 0; font-size: 12px; line-height: 18px; display: inline-flex; align-items: center; gap: 6px; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-advanced-summary:hover { color: var(--dsw-alias-brand-primary); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-advanced-summary .chev { width: 7px; height: 7px; border-right: 1.5px solid currentColor; border-bottom: 1.5px solid currentColor; transform: rotate(45deg); transition: transform 160ms; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-advanced-open .chev { transform: rotate(225deg); }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-footer { border-top: 1px solid var(--dsw-alias-border-l1); justify-content: flex-end; align-items: center; gap: 8px; margin-top: 12px; padding-top: 10px; display: flex; }',
  '[data-plugin="dsh-hippomemo"] .hippomemo-card-failed { min-width: 0; color: var(--dsw-alias-state-error-primary); flex: 1; margin: 0; font-size: 12px; line-height: 18px; }',
].join('\n')