/** CSS for the sparks section. Injected once at mount via registerSettingsSection's css option. */
export const SPARK_CSS = [
  '[data-plugin="dsh-spark-ui"] .spark-section { display: flex; flex-direction: column; gap: 16px; padding: 4px 2px 24px; color: var(--dsw-alias-label-primary); }',
  '[data-plugin="dsh-spark-ui"] .spark-title { margin: 0; color: var(--dsw-alias-label-primary); font-size: 18px; line-height: 26px; font-weight: 600; }',
  '[data-plugin="dsh-spark-ui"] .spark-intro { margin: 0; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; font-size: 13px; line-height: 20px; }',
  '[data-plugin="dsh-spark-ui"] .spark-toolbar { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; justify-content: space-between; }',
  '[data-plugin="dsh-spark-ui"] .spark-toolbar-left { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }',
  '[data-plugin="dsh-spark-ui"] .spark-toolbar-right { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }',
  '[data-plugin="dsh-spark-ui"] .spark-live { font-size: 12px; line-height: 18px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; }',
  '[data-plugin="dsh-spark-ui"] .spark-live::before { content: ""; display: inline-block; width: 6px; height: 6px; border-radius: 999px; margin-right: 6px; vertical-align: middle; background: var(--dsw-alias-state-error-primary, var(--dsw-static-red-500)); }',
  '[data-plugin="dsh-spark-ui"] .spark-live-on::before { background: var(--dsw-alias-state-success-primary, var(--dsw-static-green-500)); }',
  '[data-plugin="dsh-spark-ui"] .spark-list { display: flex; flex-direction: column; gap: 12px; }',
  '[data-plugin="dsh-spark-ui"] .spark-card { display: flex; flex-direction: column; gap: 8px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 12px; background: var(--dsw-alias-bg-layer-2); padding: 12px 14px; }',
  '[data-plugin="dsh-spark-ui"] .spark-card-head { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; justify-content: space-between; }',
  '[data-plugin="dsh-spark-ui"] .spark-card-title { font-size: 14px; line-height: 22px; font-weight: 600; color: var(--dsw-alias-label-primary); margin: 0; }',
  '[data-plugin="dsh-spark-ui"] .spark-card-content { margin: 0; font-size: 13px; line-height: 20px; color: var(--dsw-alias-label-primary); white-space: pre-wrap; }',
  '[data-plugin="dsh-spark-ui"] .spark-card-meta { display: flex; flex-wrap: wrap; gap: 6px; align-items: center; font-size: 12px; line-height: 18px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; }',
  '[data-plugin="dsh-spark-ui"] .spark-card-actions { display: flex; flex-wrap: wrap; gap: 4px; }',
  '[data-plugin="dsh-spark-ui"] .spark-card-crystallized { border-color: var(--dsw-alias-brand-primary, var(--dsw-alias-border-l1)); }',
  '[data-plugin="dsh-spark-ui"] .spark-crystallized-badge { display: inline-flex; align-items: center; gap: 4px; padding: 2px 8px; border-radius: 999px; background: var(--dsw-alias-brand-primary, var(--dsw-static-deepseek-450)); color: var(--dsw-static-white, #fff); font-size: 11px; line-height: 16px; font-weight: 600; }',
  '[data-plugin="dsh-spark-ui"] .spark-form { display: flex; flex-direction: column; gap: 8px; border: 1px solid var(--dsw-alias-border-l1); border-radius: 12px; background: var(--dsw-alias-bg-layer-2); padding: 12px 14px; }',
  '[data-plugin="dsh-spark-ui"] .spark-form-row { display: flex; flex-direction: column; gap: 4px; }',
  '[data-plugin="dsh-spark-ui"] .spark-form label { font-size: 12px; line-height: 18px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); }',
  '[data-plugin="dsh-spark-ui"] .spark-form input, [data-plugin="dsh-spark-ui"] .spark-form textarea, [data-plugin="dsh-spark-ui"] .spark-form select { border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary); padding: 6px 8px; font: inherit; }',
  '[data-plugin="dsh-spark-ui"] .spark-form textarea { min-height: 80px; resize: vertical; }',
  '[data-plugin="dsh-spark-ui"] .spark-form-actions { display: flex; gap: 8px; justify-content: flex-end; }',
  '[data-plugin="dsh-spark-ui"] .spark-empty { padding: 24px 12px; text-align: center; font-size: 13px; line-height: 20px; color: var(--dsw-alias-label-secondary, var(--dsw-alias-label-primary)); opacity: 0.72; }',
  '[data-plugin="dsh-spark-ui"] .spark-error { padding: 12px; border: 1px solid var(--dsw-alias-state-error-primary, var(--dsw-static-red-500)); border-radius: 8px; background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-state-error-primary, var(--dsw-static-red-500)); font-size: 13px; line-height: 20px; }',
].join('\n')
