/** Pure JSON wire/domain types shared by the host and client halves. */

export type MemoryId = string

export type MemoryKind =
  | 'insight'
  | 'decision'
  | 'fact'
  | 'preference'
  | 'constraint'

export type MemoryScope = 'global' | 'workspace' | 'project'

export type MemoryStatus = 'active' | 'archived' | 'superseded' | 'candidate'

export type MemoryAuthor = 'human' | 'agent' | 'system'

export interface MemoryRecord {
  id: MemoryId
  kind: MemoryKind
  title: string
  content: string
  tags: string[]
  scope: MemoryScope
  workspacePath: string | null
  /** True only when cross-workspace reach is confirmed (explicit/human). Auto-scraped globals start false so a mislabel degrades to workspace-bound. */
  globalProven: boolean
  /** Distinct workspaces where this memory has been surfaced (recall/cite), accumulating cross-workspace evidence for auto-confirming a global. */
  seenWorkspaces: string[]
  importance: number
  status: MemoryStatus
  sourceSessionId: string
  sourceAgentId?: string
  sourceTurn?: number
  /** Provenance link to the spark this memory was crystallized from (cognitive-layer Phase 2 reverse link). Null/undefined for memories created directly. */
  sourceSparkId?: string | null
  revision: number
  updatedBy: MemoryAuthor
  supersedes?: string | null
  supersededBy?: string | null
  createdAt: number
  updatedAt: number
  expiresAt: number | null
  relatedIds: string[]
  /** Extra bilingual/synonym search keywords generated at write time; indexed like tags. */
  searchTerms?: string[]
  /** How many times this memory was surfaced by search or automatic recall. */
  recallCount: number
  /** Last time this memory was surfaced (search hit or automatic recall), or null. */
  lastRecalledAt: number | null
  /** How many times this memory was cited (id mention in agent output, or a supersedes/relatedIds link). */
  citationCount: number
  /** Last time this memory was cited, or null. */
  lastCitedAt: number | null
}

export type MemorySortKey = 'updatedAt' | 'createdAt' | 'importance' | 'title'

export type MemorySortOrder = 'asc' | 'desc'

export interface MemoryListQuery {
  q?: string
  kind?: MemoryKind
  scope?: MemoryScope | 'current'
  status?: MemoryStatus
  tag?: string
  workspacePath?: string
  /** Sort key; defaults to updatedAt. */
  sort?: MemorySortKey
  /** Sort direction; defaults to desc. */
  order?: MemorySortOrder
  limit?: number
  cursor?: number
}

export interface MemoryListResult {
  items: MemoryRecord[]
  total: number
  nextCursor?: number
}

export interface MemorySearchHit {
  record: MemoryRecord
  matchedReason: string[]
}

export interface MemorySearchResult {
  items: MemorySearchHit[]
  total: number
}

export interface MemoryPutInput {
  id?: MemoryId
  kind?: MemoryKind
  title: string
  content: string
  tags?: string[]
  scope?: MemoryScope
  workspacePath?: string | null
  globalProven?: boolean
  seenWorkspaces?: string[]
  importance?: number
  status?: MemoryStatus
  sourceSessionId?: string
  sourceAgentId?: string
  sourceTurn?: number
  /** Provenance link to the spark this memory was crystallized from. Set by spark_crystallize; not user-editable. */
  sourceSparkId?: string | null
  updatedBy?: MemoryAuthor
  supersedes?: string | null
  supersededBy?: string | null
  expiresAt?: number | null
  relatedIds?: string[]
  /** Extra bilingual/synonym search keywords; normally generated by the system. */
  searchTerms?: string[]
  /** Usage counters; normally set by the system, exposed here to allow reset. */
  recallCount?: number
  lastRecalledAt?: number | null
  citationCount?: number
  lastCitedAt?: number | null
}

export interface MemoryPatchInput {
  kind?: MemoryKind
  title?: string
  content?: string
  tags?: string[]
  scope?: MemoryScope
  workspacePath?: string | null
  globalProven?: boolean
  seenWorkspaces?: string[]
  importance?: number
  status?: MemoryStatus
  sourceAgentId?: string
  sourceTurn?: number
  updatedBy?: MemoryAuthor
  supersedes?: string | null
  supersededBy?: string | null
  expiresAt?: number | null
  relatedIds?: string[]
  /** Extra bilingual/synonym search keywords; normally generated by the system. */
  searchTerms?: string[]
  /** Usage counters; normally set by the system, exposed here to allow reset. */
  recallCount?: number
  lastRecalledAt?: number | null
  citationCount?: number
  lastCitedAt?: number | null
}

export type CitationKind = 'id-ref' | 'title-ref' | 'link'

/** One recorded reference to a memory: an id mention in agent output, or a supersedes/relatedIds link. */
export interface CitationRecord {
  id: string
  memoryId: MemoryId
  sessionId: string
  kind: CitationKind
  ts: number
  /** Surrounding text of an id-ref citation, capped for storage. */
  snippet?: string
}

export interface CitationInput {
  memoryId: MemoryId
  sessionId: string
  kind: CitationKind
  snippet?: string
}

export interface CitationListQuery {
  memoryId?: MemoryId
  kind?: CitationKind
  limit?: number
  cursor?: number
}

export interface CitationListResult {
  items: CitationRecord[]
  total: number
  nextCursor?: number
}

/** One memory in a usage ranking. count is recallCount for recall ranks and citationCount for citation ranks. */
export interface MemoryUsageItem {
  id: MemoryId
  title: string
  count: number
  lastAt: number | null
}

/** Analytics over exposure (recall) vs reference (citation) of the shared memory layer. */
export interface MemoryUsageStats {
  total: number
  active: number
  /** Records surfaced at least once. */
  recalled: number
  /** Records cited at least once. */
  cited: number
  /** Records never surfaced. */
  neverRecalled: number
  /** Active records not surfaced within the staleness window. */
  staleCount: number
  /** recalled / total. */
  recallRate: number
  /** cited / total. */
  citationRate: number
  /** cited / recalled: of the memories the agent saw, how many it actually used. */
  conversionRate: number
  topRecalled: MemoryUsageItem[]
  topCited: MemoryUsageItem[]
  stale: MemoryUsageItem[]
}

export interface MemoryStats {
  total: number
  active: number
  archived: number
  superseded: number
  candidate: number
  byKind: Record<MemoryKind, number>
}

export interface HippomemoChanged {
  operation: 'put' | 'deleted'
  id: MemoryId
}
// ---- 自动进化（hippomemo-evolve）----

export type EvolveActionType =
  | 'archive'
  | 'probation'
  | 'cancel-probation'
  | 'supersede'
  | 'link'
  | 'downgrade-scope'

/** One planned/executed evolution action. */
export interface EvolveAction {
  id: string
  action: EvolveActionType
  reason: string
  /** Winner id for supersede/link actions. */
  targetId?: string
}

/** LLM review verdict for one probation candidate. */
export interface EvolveReviewVerdict {
  id: string
  verdict: 'noise' | 'keep'
  reason?: string
}

/** Result of one evolution sweep (dry-run or applied). */
export interface EvolveReport {
  runAt: number
  dryRun: boolean
  actions: EvolveAction[]
  /** When the LLM review pass ran: which candidates were kept (not probated). */
  review?: EvolveReviewVerdict[]
}

// ---- v3 UI 偏好专区 ----

/**
 * One preference-kind memory surfaced in the dedicated preference zone.
 * Carries derived hit/decay counters consumed by the UI; recall/citation
 * counters come straight from MemoryRecord.
 */
export interface PreferenceRecord {
  id: MemoryId
  title: string
  content: string
  tags: string[]
  /** 'auto' = 自动从语气强度挖（杏仁核/valence miner）; 'manual' = 用户直接声明. */
  source: 'auto' | 'manual'
  /** Times this preference was injected or matched; 0 means unused so far. */
  hitCount: number
  /** Last time the agent surfaced this preference, or null. */
  lastSurfacedAt: number | null
  /** 0..100; null = 未衰减. The auto-decayed view consumed in the UI. */
  decayPercent: number | null
  /** User has confirmed this preference is durable (rejects decay floor). */
  confirmed: boolean
  status: MemoryStatus
  updatedAt: number
}

export interface PreferenceListQuery {
  /** Only surface preferences whose decay has dropped under this percent. */
  decayFloor?: number
  /** Source filter; undefined = both. */
  source?: PreferenceRecord['source']
}

export interface PreferenceListResult {
  items: PreferenceRecord[]
  total: number
}

// ---- v3 UI 待处理候选（F11 落地前的轻量版） ----

/**
 * Live candidate surfaced from the deterministic sweep: the existing
 * planEvolution() outcome for the current record set, classified into one
 * of the action quadrants the UI shows in the "needs my attention" panel.
 * No writes happen on read; resolution still goes through PATCH on the
 * underlying record.
 */
export type CandidateKind = 'expired' | 'near-duplicate' | 'observation' | 'preference-review'

export interface PendingCandidate {
  id: MemoryId
  kind: CandidateKind
  title: string
  /** Free-text reason (human-readable). */
  reason: string
  /** Memory kind, surfaced for the pill. */
  memoryKind: MemoryKind
  /** Suggested action label from the corresponding EvolveAction. */
  suggestedAction: EvolveActionType
  /** For near-duplicate candidates, the winner id. */
  targetId?: MemoryId
  /** Importance (so the UI can sort within a kind). */
  importance: number
  /** When the candidate was first detected (now()). */
  detectedAt: number
}

export interface PendingCandidateListResult {
  items: PendingCandidate[]
  /** Aggregated counts by kind for the brain-strip + header. */
  byKind: Record<CandidateKind, number>
  total: number
}

// ---- v3 UI 脑区旁白（F10 召回事件落地前的轻量版） ----

/**
 * Brain-strip narration row. Without the full F10 recall-event table the
 * narrator is synthesised from the latest citation + current totals so the
 * strip still animates against real events.
 */
export interface RecallNarrative {
  /** Short caption shown in the brain strip footer. */
  text: string
  /** Region that should pulse when this narrative is rendered. */
  region: 'pfc' | 'amy' | 'hippo' | 'cortex'
  /** Epoch ms; UI uses this to decide whether to retrigger the pulse. */
  ts: number
  /** Optional citation snippet backing the narration. */
  snippet?: string
}

