/** Pure JSON wire/domain types shared by the host and client halves. */

export type MemoryId = string

export type MemoryKind =
  | 'insight'
  | 'decision'
  | 'fact'
  | 'preference'
  | 'constraint'

export type MemoryScope = 'global' | 'workspace' | 'project'

export type MemoryStatus = 'active' | 'archived' | 'superseded' | 'candidate'

export type MemoryAuthor = 'human' | 'agent' | 'system'

export interface MemoryRecord {
  id: MemoryId
  kind: MemoryKind
  title: string
  content: string
  tags: string[]
  scope: MemoryScope
  workspacePath: string | null
  /** True only when cross-workspace reach is confirmed (explicit/human). Auto-scraped globals start false so a mislabel degrades to workspace-bound. */
  globalProven: boolean
  importance: number
  status: MemoryStatus
  sourceSessionId: string
  sourceAgentId?: string
  sourceTurn?: number
  revision: number
  updatedBy: MemoryAuthor
  supersedes?: string | null
  supersededBy?: string | null
  createdAt: number
  updatedAt: number
  expiresAt: number | null
  relatedIds: string[]
  /** Extra bilingual/synonym search keywords generated at write time; indexed like tags. */
  searchTerms?: string[]
  /** How many times this memory was surfaced by search or automatic recall. */
  recallCount: number
  /** Last time this memory was surfaced (search hit or automatic recall), or null. */
  lastRecalledAt: number | null
  /** How many times this memory was cited (id mention in agent output, or a supersedes/relatedIds link). */
  citationCount: number
  /** Last time this memory was cited, or null. */
  lastCitedAt: number | null
}

export type MemorySortKey = 'updatedAt' | 'createdAt' | 'importance' | 'title'

export type MemorySortOrder = 'asc' | 'desc'

export interface MemoryListQuery {
  q?: string
  kind?: MemoryKind
  scope?: MemoryScope | 'current'
  status?: MemoryStatus
  tag?: string
  workspacePath?: string
  /** Sort key; defaults to updatedAt. */
  sort?: MemorySortKey
  /** Sort direction; defaults to desc. */
  order?: MemorySortOrder
  limit?: number
  cursor?: number
}

export interface MemoryListResult {
  items: MemoryRecord[]
  total: number
  nextCursor?: number
}

export interface MemorySearchHit {
  record: MemoryRecord
  matchedReason: string[]
}

export interface MemorySearchResult {
  items: MemorySearchHit[]
  total: number
}

export interface MemoryPutInput {
  id?: MemoryId
  kind?: MemoryKind
  title: string
  content: string
  tags?: string[]
  scope?: MemoryScope
  workspacePath?: string | null
  globalProven?: boolean
  importance?: number
  status?: MemoryStatus
  sourceSessionId?: string
  sourceAgentId?: string
  sourceTurn?: number
  updatedBy?: MemoryAuthor
  supersedes?: string | null
  supersededBy?: string | null
  expiresAt?: number | null
  relatedIds?: string[]
  /** Extra bilingual/synonym search keywords; normally generated by the system. */
  searchTerms?: string[]
  /** Usage counters; normally set by the system, exposed here to allow reset. */
  recallCount?: number
  lastRecalledAt?: number | null
  citationCount?: number
  lastCitedAt?: number | null
}

export interface MemoryPatchInput {
  kind?: MemoryKind
  title?: string
  content?: string
  tags?: string[]
  scope?: MemoryScope
  workspacePath?: string | null
  globalProven?: boolean
  importance?: number
  status?: MemoryStatus
  sourceAgentId?: string
  sourceTurn?: number
  updatedBy?: MemoryAuthor
  supersedes?: string | null
  supersededBy?: string | null
  expiresAt?: number | null
  relatedIds?: string[]
  /** Extra bilingual/synonym search keywords; normally generated by the system. */
  searchTerms?: string[]
  /** Usage counters; normally set by the system, exposed here to allow reset. */
  recallCount?: number
  lastRecalledAt?: number | null
  citationCount?: number
  lastCitedAt?: number | null
}

export type CitationKind = 'id-ref' | 'title-ref' | 'link'

/** One recorded reference to a memory: an id mention in agent output, or a supersedes/relatedIds link. */
export interface CitationRecord {
  id: string
  memoryId: MemoryId
  sessionId: string
  kind: CitationKind
  ts: number
  /** Surrounding text of an id-ref citation, capped for storage. */
  snippet?: string
}

export interface CitationInput {
  memoryId: MemoryId
  sessionId: string
  kind: CitationKind
  snippet?: string
}

export interface CitationListQuery {
  memoryId?: MemoryId
  kind?: CitationKind
  limit?: number
  cursor?: number
}

export interface CitationListResult {
  items: CitationRecord[]
  total: number
  nextCursor?: number
}

/** One memory in a usage ranking. count is recallCount for recall ranks and citationCount for citation ranks. */
export interface MemoryUsageItem {
  id: MemoryId
  title: string
  count: number
  lastAt: number | null
}

/** Analytics over exposure (recall) vs reference (citation) of the shared memory layer. */
export interface MemoryUsageStats {
  total: number
  active: number
  /** Records surfaced at least once. */
  recalled: number
  /** Records cited at least once. */
  cited: number
  /** Records never surfaced. */
  neverRecalled: number
  /** Active records not surfaced within the staleness window. */
  staleCount: number
  /** recalled / total. */
  recallRate: number
  /** cited / total. */
  citationRate: number
  /** cited / recalled: of the memories the agent saw, how many it actually used. */
  conversionRate: number
  topRecalled: MemoryUsageItem[]
  topCited: MemoryUsageItem[]
  stale: MemoryUsageItem[]
}

export interface MemoryStats {
  total: number
  active: number
  archived: number
  superseded: number
  candidate: number
  byKind: Record<MemoryKind, number>
}

export interface HippomemoChanged {
  operation: 'put' | 'deleted'
  id: MemoryId
}
// ---- 自动进化（hippomemo-evolve）----

export type EvolveActionType =
  | 'archive'
  | 'probation'
  | 'cancel-probation'
  | 'supersede'
  | 'link'

/** One planned/executed evolution action. */
export interface EvolveAction {
  id: string
  action: EvolveActionType
  reason: string
  /** Winner id for supersede/link actions. */
  targetId?: string
}

/** LLM review verdict for one probation candidate. */
export interface EvolveReviewVerdict {
  id: string
  verdict: 'noise' | 'keep'
  reason?: string
}

/** Result of one evolution sweep (dry-run or applied). */
export interface EvolveReport {
  runAt: number
  dryRun: boolean
  actions: EvolveAction[]
  /** When the LLM review pass ran: which candidates were kept (not probated). */
  review?: EvolveReviewVerdict[]
}
